### ISSUE TITLE
@ionic-native/file hangs when trying to save to application directory

### ISSUE THREAD

**Issue by connor-odoherty** [ionic-team/cordova-plugin-ionic-webview#30] opened 2017-10-26 02:09 UTC
Prior to using WKWebView, I was able to use the Cordova File plugin to write files, create directories, and check for files using the dataDirectory path of the File plugin. After I installed WKWebview, requests to writeFile began to hang. I don't receive a success or failure message, and I don't catch an exception, it just hangs.

Looking over other people's issues, it seems like WKWebView has an issue with file:// prefixes. The file plugin uses file:// for its dataDirectory constant. Using normalizeURL (a suggested fix) just prefixes my file path with localhost, which does not work on mobile devices.

What can I do to use the Cordova File plugin and save images to the application directory? Am I going about this incorrectly?

**Comment by johannds** [comment] 2017-10-26 21:45
I'm seeing the same thing, as well as issues related to cdvfile://

**Comment by EtienneLem** [comment] 2017-11-16 20:13
Had the same issue even when long-pressing an image and tapping **Save Image**. Was fixed by adding `NSPhotoLibraryAddUsageDescription` to my config, as documented here https://github.com/apache/cordova-plugin-camera#ios-quirks.

It is now [required since iOS 11](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html).

**Comment by johannds** [comment] 2017-11-16 21:05
+1 Thanks @Etienne, I had the same experience.

**Comment by jcesarmobile** [comment] 2019-08-23 16:31
I can't reproduce with latest version of the plugin, but if the problem persists, please, create a new issue and provide a sample app.

**Closed by jcesarmobile** 2019-08-23 16:31 UTC
