### ISSUE TITLE
(Fixed) Snaps to top of screen on blur on iOS 12+

### ISSUE THREAD

**Issue by MitchEff** [ionic-team/cordova-plugin-ionic-webview#399] opened 2019-07-18 02:17 UTC
After _days_ of screwing around with other plugins/settings/native code/angry users/bottles of wine I've discovered THIS plugin is to blame.

As of recently (I'm not sure exactly when), when you focus a text input, then un-focus it, the screen **rockets** up to the top. There's nothing you can do about it. I've tried:

- `disableScroll(true)`
- `shrinkView`
- `automaticScrollToTopOnHiding = false`
- manually getting/setting scrollTop on `keyboardWillHide`/`keyboardDidHide`
- howling at the moon

I'd nearly lost my mind until I removed this webview and used Apache's `cordova-plugin-wkwebview-engine`. It miraculously stopped acting like it was possessed by a demon, and all was well in the world.

Surely other people are encountering this?

**Comment by Serivy** [comment] 2019-07-19 09:03
I have been going down this rabbit hole myself trying to find a solution. You're seeing this behavior due to this 'fix'.
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/176
in this pull request https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/201

The cordova have a matching bug which has remained unresolved 
https://github.com/apache/cordova-plugin-wkwebview-engine/issues/71
which they tried to use the ionic fix in this pull request
https://github.com/apache/cordova-plugin-wkwebview-engine/pull/75
but it was rejected because people noticed scrolling to the top is often not the intended behavior.
There are JS fixes which do similar (scroll to top)

At present it seems the only solution is to downgrade to XCode 9.

**Comment by MitchEff** [comment] 2019-07-19 09:20
That makes so much sense, Serivy. I just moved from Ionic's WKWebview back to Apache's one cause of the abhorrent scroll-to-top thing. I thought it was just a bug.

If I downgrade to Xcode 9, wouldn't I then be unable to use iOS 12 SDK? I was considering that for ages but then read Apple won't approve any apps that don't use the iOS 12 SDK.

**Comment by Serivy** [comment] 2019-07-19 10:01
Yep, i'm in a similar situation (except I'm not using ionic), i don't want to down grade, and i can't switch back to the old web view (because of rendering bugs that forced us to upgrade), so all I can hope is apple fixes it soon, but doesn't look like a lot of movement given the feedback in those links to apple support.

**Comment by Serivy** [comment] 2019-07-23 10:07
As an update, I got a XCode 10.3 (10G8) today on my build server and fingers crossed it looks like it works (without the scroll to top fix) while deployed to test flight. That being said i found experimenting on my development xcode of 10.2.1 (10E1001) deployed to device didn't have this problem but couldn't get our build server to replicate it.

**Comment by MitchEff** [comment] 2019-07-23 13:31
Cordova's WKWebview and Ionic keyboard with keyboardResizeMode set to body seemed to fix all my scrolling/keyboard/screen issues. It doesn't jump to the top anymore and all works fairly predictably.

It's not great at scrolling down when inputs are focused, but that's pretty easily fixed with JS.

**Comment by Amaury-T** [comment] 2020-01-28 16:40
So there is no other solution than ditching this plugin and use Cordova WKWebview instead?

**Comment by MitchEff** [comment] 2020-01-28 22:28
In my experience, yeah. I couldn't find any way around it.

**Comment by Gillardo** [comment] 2020-02-07 10:25
I am experiencing this issue as well, when will it be fixed?

**Comment by sajallimbu** [comment] 2020-02-13 05:29
Any fix yet?

**Comment by sajallimbu** [comment] 2020-02-13 10:56
I fixed the issue with this 
https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/342#issuecomment-585644871

**Comment by andaralex** [comment] 2020-04-06 12:50
As recommended, shall I use this plugin **cordova-plugin-wkkeyboardfix**?
Is anyone used and publish their app in Apple Store? because they have given note as - plugin is a hack around a bug in iOS. It might result in your app being rejected from the App Store! Use this at your own risk.

**Comment by jcesarmobile** [comment] 2020-04-10 16:16
fixed in https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/533

**Closed by jcesarmobile** 2020-04-10 16:16 UTC
