### ISSUE TITLE
Failed to load webpage with error: The network connection was lost.

### ISSUE THREAD

**Issue by Wade-McDaniel** [ionic-team/cordova-plugin-ionic-webview#17] opened 2017-10-09 14:28 UTC
I've followed the directions here: https://github.com/ionic-team/cordova-plugin-ionic-webview

But when I start debugging on an actual iOS11 device through XCode, the app splash screen loads, and in the XCode Debug area the last message I see is "**Failed to load webpage with error: The network connection was lost."**

How do I go about debugging/solving this?

I don't have this app publicly view-able on github, but here are the relevant parts of my config.xml:

    ....
    <access allows-arbitrary-loads-in-media="true" allows-arbitrary-loads-in-web-content="true" origin="*" />
    <allow-navigation href="http://localhost:8080/*" />
    <allow-navigation href="http://localhost:0/*" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <branch-config>
        <branch-key value="key_live_12345" />
        <uri-scheme value="my-scheme" />
        <link-domain value="my-website.com" />
        <link-domain value="my-website.app.link" />
        <ios-team-release value="ABCDE" />
        <ios-team-id value="ABCDE" />
        <host name="my-website.app.link" scheme="https" />
        <host name="my-website-alternate.app.link" scheme="https" />
        <android-prefix value="/WSuf" />
    </branch-config>
    <preference name="AndroidLaunchMode" value="singleTask" />
    <preference name="AlternateContentSrc" value="http://localhost:0" />
    <engine name="android" spec="^6.3.0" />
    <engine name="ios" spec="^4.5.1" />
    <plugin name="branch-cordova-sdk" spec="^2.6.14">
        <variable name="BRANCH_KEY" value="key_live_12345" />
        <variable name="URI_SCHEME" value="my-scheme" />
    </plugin>
    <plugin name="cordova-plugin-app-version" spec="^0.1.9" />
    <plugin name="cordova-plugin-background-mode" spec="git+https://github.com/Wade-McDaniel/cordova-plugin-background-mode.git" />
    <plugin name="cordova-plugin-device" spec="^1.1.6" />
    <plugin name="cordova-plugin-dialogs" spec="^1.3.3" />
    <plugin name="cordova-plugin-facebook" spec="^0.2.2">
        <variable name="FACEBOOK_DISPLAY_NAME" value="My FB App" />
        <variable name="FACEBOOK_APP_ID" value="12235" />
    </plugin>
    <plugin name="cordova-plugin-google-analytics" spec="^1.6.0" />
    <plugin name="cordova-plugin-googleplus" spec="^5.1.1">
        <variable name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.12345" />
    </plugin>
    <plugin name="cordova-plugin-inappbrowser" spec="^1.5.0" />
    <plugin name="cordova-plugin-ionic-webview" spec="^1.1.14" />
    <plugin name="cordova-plugin-media" spec="git+https://github.com/Wade-McDaniel/cordova-plugin-media.git" />
    <plugin name="cordova-plugin-music-controls" spec="git+https://github.com/Wade-McDaniel/cordova-music-controls-plugin.git" />
    <plugin name="cordova-plugin-network-information" spec="^1.3.3" />
    <plugin name="cordova-plugin-screen-orientation" spec="^1.4.3" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-statusbar" spec="^2.2.3" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.1.8" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    ....

Here's the text from the Debug Area in XCode:

    Apache Cordova native platform version 4.5.0 is starting.
    Multi-tasking -> Device: YES, App: YES
    CDVWKWebViewEngine: trying to inject XHR polyfill
    [MC] Lazy loading NSBundle MobileCoreServices.framework
    [MC] Loaded MobileCoreServices.framework
    [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
    CDVWKWebViewEngine will reload WKWebView if required on resume
    Using Ionic WKWebView
    [CDVTimer][console] 0.176013ms
    [CDVTimer][handleopenurl] 0.238001ms
    [CDVTimer][intentandnavigationfilter] 3.488004ms
    [CDVTimer][gesturehandler] 0.129044ms
    [CDVTimer][branchsdk] 0.187993ms
    [CDVTimer][cordovafacebook] 1.803994ms
    [CDVTimer][googleplus] 0.118017ms
    [CDVTimer][file] 3.505051ms
    [CDVTimer][splashscreen] 70.317030ms
    [CDVTimer][statusbar] 11.494994ms
    [MC] Filtering mail sheet accounts for bundle ID: com.myapp.mobile, source account management: 1
    [MC] Filtering mail sheet accounts for bundle ID: com.myapp.mobile, source account management: 1
    [CDVTimer][socialsharing] 93.789041ms
    [CDVTimer][keyboard] 2.359033ms
    [CDVTimer][TotalPluginStartup] 189.309955ms
    refreshPreferences: HangTracerEnabled: 0
    refreshPreferences: HangTracerDuration: 500
    refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
    [MC] Reading from public effective user settings.
    Failed to load webpage with error: The network connection was lost.

Thank you for your help!

**Comment by Wade-McDaniel** [comment] 2017-10-09 14:43
I tried removing cordova-plugin-backround-mode because I saw that mentioned as a thing to try, to no avail.

Also, in a seperate ionic app with essentially the same config, on that I haven't upgraded yet, the line I see after "Reading from public effective user settings" is "Resetting plugins due to page load". So that means this app is probably dieing during WKWebView initialization, event before it tries to load anything form the files on the device, right?

**Comment by Wade-McDaniel** [comment] 2017-10-09 14:51
I also tried upgrading to v1.1.15 of this plugin, but that didn't seem to change what I see in the XCode Debug Area.

**Comment by Wade-McDaniel** [comment] 2017-10-09 17:11
I also went one-by-one through the plugins running "ionic cordova plugin remove [plugin name]" except for cordova-plugin-ionic-webview, and after removing each one I'd re-launch XCode and trying debugging on the iPhone again, and the app got stuck on "Failed to load webpage with error: The network connection was lost." each time.

I also searched through the plugins directory for "network connection was lost" in case a plugin was doing this, but didn't find any matches there.

So if that's the correct way to eliminate other plugins as the reason for this issue, then I think this has to be cordova-plugin-ionic-webview failing for some reason, right?

I'm going to look now for a way to get more verbose output in XCode so I can perhaps see the request that is failing.

**Comment by Wade-McDaniel** [comment] 2017-10-09 17:57
I'm not super familiar with XCode, but it looks like the GCDWebServer is listening at localhost:8080 but the first page that tries to load is localhost:0. So I tried removing this from config.xml (<preference name="AlternateContentSrc" value="http://localhost:0" />) but that didn't change anything.

**Comment by Wade-McDaniel** [comment] 2017-10-09 21:34
My last thought was to set the AlternateContentSrc preference in config.xml to http://localhost:8080, but that didn't do anything either.

So the error is visible if I set a breakpoint in this method in CDVWebViewEngine.m
(void)webView:(WKWebView*)theWebView didFailNavigation:(WKNavigation*)navigation withError:(NSError*)error
I set a breakpoint in there in XCode in such a way that I can look at the "vc" MainViewController variable, and that has a "startPage" of "http://localhost:0".

Any help for me here...please? :)

**Comment by recap** [comment] 2017-10-19 10:32
I have a similar issue. I get Failed to load webpage with error: Could not connect to the server when app is started in background after being suspended. This error happens immediately on startup:

CDVWKWebViewEngine: trying to inject XHR polyfill
CDVWKWebViewEngine will reload WKWebView if required on resume
Using Ionic WKWebView
...loading plugins
[CDVTimer][TotalPluginStartup] 181.908011ms
Failed to load webpage with error: Could not connect to the server. 

The error happens in CDVWKWebViewEngine.m and after this error the app hangs indefinitely.

Have not found a solution for this so any help would be greatly appreciated.

**Comment by ghenry22** [comment] 2017-11-15 03:49
@Wade-McDaniel looking at your config.xml and comparing with mine:
remove
`    <allow-navigation href="http://localhost:0/*" /> as you can't use port 0`
add
```
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
```
remove the ionic-webview plugin and re-install it then run
ionic cordova prepare
ionic cordova build ios

and see if it runs.

Before you try to run the app try closing any other apps.

Are you launching the app just by running it through xcode or tapping the app icon or in some other way?

@recap - you say "when the app is started in the background"  What happens if you start the app normally by tapping the icon, does it work?

**Comment by jcesarmobile** [comment] 2018-09-11 11:06
Please, update to latest version and try again, the plugin has changed a lot lately and I can't reproduce this with latest version. If problem persist, create a new issue and provide more information.

**Closed by jcesarmobile** 2018-09-11 11:06 UTC

**Comment by askona** [comment] 2018-10-14 09:41
It's happend to me with plugin v.2.1.4

**Comment by KenCorbettJr** [comment] 2019-05-17 21:54
I had this error and just removed the <allow-navigation line from my config and I was working again.

**Comment by namlongsoft** [comment] 2020-02-06 09:31
> I have a similar issue. I get Failed to load webpage with error: Could not connect to the server when app is started in background after being suspended. This error happens immediately on startup:
> 
> CDVWKWebViewEngine: trying to inject XHR polyfill
> CDVWKWebViewEngine will reload WKWebView if required on resume
> Using Ionic WKWebView
> ...loading plugins
> [CDVTimer][TotalPluginStartup] 181.908011ms
> Failed to load webpage with error: Could not connect to the server.
> 
> The error happens in CDVWKWebViewEngine.m and after this error the app hangs indefinitely.
> 
> Have not found a solution for this so any help would be greatly appreciated.

Did you find any solution yet? I have some problem and have to kill app then reopen.
