### ISSUE TITLE
Unable to open local html file in inappbrowser: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by expcapitaldev** [ionic-team/cordova-plugin-ionic-webview#197] opened 2018-10-19 11:31 UTC
I'm trying to open local html file via inappbrowser. The file is stored in www (root) folder. As expected, opening file was impossible after upgrade from version 1.2.1, however I'm not able to make it work. Initially I simply passed file name to browser

`const url = "form.html?";`

After updating web view I've changed it to

`const url = (<any>window).Ionic.WebView.convertFileSrc("form.html");`

I'm still getting **The webpage at http://localhost:8080/form.html could not be loaded because net::ERR_CONNECTION_REFUSED**. I've also tried using 

`const url = (<any>window).Ionic.WebView.convertFileSrc("file://form.html");`

but nothing changed. Am I missing something?

**Comment by davec21** [comment] 2018-10-19 18:40
I too am getting this issue, not sure if it's because in-app browser runs outside of the ionic app? I ended up just creating a new view that is effectively just an iframe/viewer to make it work.

**Comment by jcesarmobile** [comment] 2018-11-06 17:18
Duplicate of https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/178

**Closed by jcesarmobile** 2018-11-06 17:18 UTC
