### ISSUE TITLE
Fullscreen video in landscape breaks statusbar and webview when closing - iOS

### ISSUE THREAD

**Issue by tmk1991** [ionic-team/cordova-plugin-ionic-webview#297] opened 2019-02-02 20:25 UTC
When you open a video in fullscreen and put the phone in landscape orientation and then return back to the page, the whole app content slides up and breaks the view. Items are underneath the statusbar and ultimately makes the app un-usable until force closing and re-opening.

Issue happening on iOS fullscreen.

**Comment by jcesarmobile** [comment] 2019-02-04 13:39
Do you have `cordova-plugin-statusbar` installed? as far as I remember, this was an issue with that plugin.

**Comment by tmk1991** [comment] 2019-02-04 17:05
I do have that plugin, however this issue is not similar to that one. In the issue you're referring to, the plugin was crashing and the statusbar was disappearing entirely.

In this case, the statubar is fine and I can programmatically show / hide it after as expected. The positioning of the webview is what is off.  :(

**Comment by jcesarmobile** [comment] 2019-02-05 12:05
I can't reproduce, can you provide a sample app?

**Comment by jcesarmobile** [comment] 2019-02-12 11:30
I couldn't reproduce and no sample app was provided after a week, so closing as can't reproduce.

**Closed by jcesarmobile** 2019-02-12 11:30 UTC

**Comment by tmk1991** [comment] 2019-02-13 02:45
Hi @jcesarmobile  sorry for the delay. Here's a video of it failing: 
https://drive.google.com/open?id=1h9vic79NY7W5mzjT-Z1mOWvzLc1ryTZe

**Comment by desmeit** [comment] 2019-03-16 08:15
i have the same problem. is there a solution yet? I have set the app to fullscreen. In the settings I have:

```
<custom-config-file parent="UIStatusBarHidden" platform="ios" target="*-Info.plist">
    <true/>
</custom-config-file>
<custom-config-file parent="UIViewControllerBasedStatusBarAppearance" platform="ios" target="*-Info.plist">
    <false/>
</custom-config-file>
```

when I close a video, it breaks the the statusbar an I see a white area from the statusbar. how can this be prevented?
