### ISSUE TITLE
video and audio not work in Android 7 with chrome v51

### ISSUE THREAD

**Issue by hugodaniel75** [ionic-team/cordova-plugin-ionic-webview#372] opened 2019-06-04 07:12 UTC
My app work in android 8,9 but in android 7 all videos and audios in local storage not work. I have uninstalled the webview plugin and the videos and audios work correctly in the different versions. Which is an error in this plugin.

**Comment by jcesarmobile** [comment] 2019-06-04 16:46
What is your plugin version?
Does it work if you update Chrome?

**Comment by hugodaniel75** [comment] 2019-06-04 18:12
I have last versión ionic webview. The smartphone is Meizu.

**Comment by jcesarmobile** [comment] 2020-03-27 17:54
Some chrome versions had problems, but I can't reproduce now, so closing.

**Closed by jcesarmobile** 2020-03-27 17:54 UTC
