### ISSUE TITLE
Releasenotes not up to date

### ISSUE THREAD

**Issue by Klaasvaak** [ionic-team/cordova-plugin-ionic-webview#43] opened 2017-11-07 09:21 UTC
I noticed https://github.com/ionic-team/cordova-plugin-wkwebview-engine is deprecated. So I will move to this repo. I would like to see the changes you made since the repo rename but the Releasenotes does not seem to be up to date.

**Comment by corran2go** [comment] 2018-01-05 12:28
It's easy to state "This plugin is an extension of the Apache Cordova WKWebView plugin." and telling everybody to use this one.

But without keeping the ReleaseNotes up-to-date and following the updates on the original code base this is just a waste of time...

**Comment by jcesarmobile** [comment] 2018-09-11 11:15
Closing as duplicate of https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/11

**Closed by jcesarmobile** 2018-09-11 11:15 UTC
