### ISSUE TITLE
angular does not bootstrap on first load

### ISSUE THREAD

**Issue by forumics** [ionic-team/cordova-plugin-ionic-webview#529] opened 2020-03-14 04:25 UTC
upon first install, i'm always getting a white screen.
upon inspect it seems like angular is not bootstrapping and javascript does not seem to be triggering.

as a workaround i'm doing this at the moment

Plugins > CDVWKWebViewEngine.m > -webView:didFinishNavigation
- (void)webView:(WKWebView*)webView didFinishNavigation:(WKNavigation*)navigation
{
    CDVViewController* vc = (CDVViewController*)self.viewController;
    [CDVUserAgentUtil releaseLock:vc.userAgentLockToken];

    [[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:CDVPageDidLoadNotification object:webView]];
    NSLog (@ "All pages loaded %@", webView.URL.absoluteString);
    if ([webView.URL.absoluteString.lowercaseString  isEqual: @"ionic://localhost"]) {
      NSLog(@"%@", @"CDVWKWebViewEngine loading failed!");
        [(WKWebView*)_engineWebView reload];
    }
}

i'm not an iOS developer but this seems to work for me for now.

anybody else encountering this issue?

my plugins list
com.darktalker.cordova.screenshot 0.1.6 "com.darktalker.cordova.screenshot"
cordova-instagram-plugin 0.5.8 "Instagram"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-deeplinks 1.1.1 "Cordova Deeplinks Plugin"
cordova-plugin-device 2.0.3-dev "Device"
cordova-plugin-facebook4 6.2.0 "Facebook Connect"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2-dev "Network Information"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-ionic-xhr 2.1.1 "Cordova WKWebView Ionic XHR Plugin"
cordova-plugin-x-socialsharing 5.6.0 "SocialSharing"
cordova-plugin-x-toast 2.7.2 "Toast"
cordova-universal-clipboard 0.1.0 "Clipboard"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"

**Comment by tamvcspk** [comment] 2020-03-17 08:15
Me too, but I realize that there's an undefined variable that prevents the app from bootstrapping after I use 'alert' instead of 'console.log'.

**Comment by forumics** [comment] 2020-03-17 09:07
what is the variable in your case? 
is your variable from angular or native?

**Comment by tamvcspk** [comment] 2020-03-17 09:11
It's `window.plugins.Permission`.I created a service and in its constructor the variable is undefined so angular failed to bootstrap

**Comment by forumics** [comment] 2020-03-17 09:17
any errors thrown from log?
in my case i can see <app></app> and no logs are generated

**Comment by tamvcspk** [comment] 2020-03-17 09:30
Me too and that drives me crazy.
I use `alert` instead of `log`. Then the bug appears

**Comment by jcesarmobile** [comment] 2020-04-10 17:11
I'm closing because it looks like an user error to me, in tamvcspk case it looks like they are trying to use `window.plugins.Permission` before device ready or the plugin that adds that variable is not installed.
For forumics it's unclear because didn't provide enough information.

Feel free to reopen or create a new issue if you can provide a sample app where the issue is reproducible.

**Closed by jcesarmobile** 2020-04-10 17:11 UTC
