### ISSUE TITLE
Custom scheme not working on Android

### ISSUE THREAD

**Issue by gabriele-sacchi** [ionic-team/cordova-plugin-ionic-webview#348] opened 2019-04-16 16:20 UTC
I am developing (and near to the release) of a Cordova App for iOS and Android.

MY CONFIG:

```
    <allow-navigation href="cordovaios://*" />
    <allow-navigation href="cordovaandroid://*" />
```

```
    <plugin name="cordova-plugin-ionic-webview" spec="^4.0.0">
        <variable name="ANDROID_SUPPORT_ANNOTATIONS_VERSION" value="27.+" />
    </plugin>
    <preference name="Hostname" value="my-backend-url-to-avoid-CORS.com" />
    <preference name="iosScheme" value="cordovaios" />
    <preference name="Scheme" value="cordovaandroid" />
    <preference name="ScrollEnabled" value="true" />
    <preference name="MixedContentMode" value="0" />
    <preference name="AllowBackForwardNavigationGestures" value="true" />
    <preference name="Allow3DTouchLinkPreview" value="false" />
    <preference name="WKSuspendInBackground" value="false" />
    <preference name="KeyboardAppearanceDark" value="false" />
```

OUTCOME:

**The App crashes on launch.**

LOGS:

```
> 10:46:48.891 5726-5770/mycertificate.enterprise D/SERVER: Handling local request: cordovaandroid://my-backend-url-to-avoid-CORS.com/static/js/10.601e7973.chunk.js
> 10:46:48.929 5726-5773/mycertificate.enterprise E/chromium: [ERROR:render_process_host_impl.cc(4070)] Terminating render process for bad Mojo message: Received bad user message: Origin is invalid
> 10:46:48.929 5726-5773/mycertificate.enterprise E/chromium: [ERROR:bad_message.cc(23)] Terminating renderer for bad IPC message, reason 123
```

NOTE: 

This config works fine on iOS. On Android I can't use this plugin due to this Origin issue.

( [I raised this issue also on Stackoverflow](https://stackoverflow.com/questions/55712710/cordova-plugin-ionic-webview-custom-scheme-not-working-on-android) )

**Comment by gabriele-sacchi** [comment] 2019-04-18 20:11
( Added a 100 bounty on Stackoverflow )

**Comment by jcesarmobile** [comment] 2019-04-23 17:48
I can't reproduce on a simple Cordova app that just have the plugin.
Can you provide more information? Like Android version of the device, user agent of the device when running the app (just do `console.log(navigator.userAgent);`).
Also, what does your app do?
The mojo errors are usually caused by unsupported css features or things that it considers insecure for some reason. 
Can you provide a minimal app that reproduces the issue?

**Comment by jcesarmobile** [comment] 2019-06-05 11:18
closing as I couldn't reproduce and the requested information was not provided.

**Closed by jcesarmobile** 2019-06-05 11:18 UTC
