### ISSUE TITLE
iOS: fail to load gapi.client on V2.3.2 + 

### ISSUE THREAD

**Issue by xinfengmich** [ionic-team/cordova-plugin-ionic-webview#345] opened 2019-04-12 17:29 UTC
I use ng-gapi to load the google calendar api,  it works fine with V2.3.1 on both Android and iOS.   But with V2.3.2 + , gapi is loaded, but not gapi.client on iOS.  console logs are following:

[Log] subscription gapiService.onLoad – true (cordova.js, line 1732)
[Log] gapi is ready :  (cordova.js, line 1732)
Object

_: {b: function, _DumpException: function, aa: Array, PK: function, jb: function, …}

auth2: {init: function, authorize: function, _gt: function, enableDebugLogs: function, getAuthInstance: function, …}

config: {get: function, update: function}

load: function(a,b)

loaded_0: function(u)

loaded_1: null

Object Prototype

[Error] gapi.client failed to load!
	(anonymous function) (cordova.js:1732)
	onerror (default~academic-events-academic-events-module~after-hours-transit-detail-after-hours-transit-detail~4f41cd1f.js:245)
	wa (api.js:11)
	xa (api.js:8)
	ea (api.js:9:507)
	B (api.js:10:225)
	(anonymous function) (api.js:10:329)
	(anonymous function) (api.js:10:390)
	Global Code (cb=gapi.loaded_0:1)
[Error] onerror:  – {"line":150,"column":426,"sourceURL":"https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_US.8RodOolT8JU.O/m=client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCOIo0_JuSGflMsDv4KwJaDwWj-arA/cb=gapi.loaded_0"}
	(anonymous function) (cordova.js:1732)
	onerror (default~academic-events-academic-events-module~after-hours-transit-detail-after-hours-transit-detail~4f41cd1f.js:246)
	wa (api.js:11)
	xa (api.js:8)
	ea (api.js:9:507)
	B (api.js:10:225)
	(anonymous function) (api.js:10:329)
	(anonymous function) (api.js:10:390)
	Global Code (cb=gapi.loaded_0:1)

[Log] gapi.load finish loading client, gapi.client =  – undefined (cordova.js, line 1732)
[Log] initCalendarClient executing ...  (cordova.js, line 1732)
[Error] TypeError: undefined is not an object (evaluating 'gapi.client.load')
	initCalendarClient (default~academic-events-academic-events-module~after-hours-transit-detail-after-hours-transit-detail~4f41cd1f.js:280)
	callback (default~academic-events-academic-events-module~after-hours-transit-detail-after-hours-transit-detail~4f41cd1f.js:233)
	(anonymous function) (api.js:10:250)
	fa (api.js:3:679)
	B (api.js:10:234)
	(anonymous function) (api.js:10:329)
	(anonymous function) (api.js:10:390)
	Global Code (cb=gapi.loaded_0:1)

... ... 

From what I saw line 150 in cb=gapi.loaded_0.js,  I wonder if it's related to iosScheme "ionic://".

**Comment by simonthb** [comment] 2019-04-14 17:50
May I ask you something? I'm planning to use Cordova/Ionic to communicate with Google API such as Google Sheets API v4.0. A basic issue is really, that Cordova apps (and other webviews) are not supported by gapi.client. Because Google is only allowing to run a simple request on the first level with just an api key from cordova base without browser environment. 

<img width="751" alt="Screenshot 2019-04-14 at 19 45 08" src="https://user-images.githubusercontent.com/49618516/56096879-d7113500-5eed-11e9-9e82-20233a14e08d.png">

So, you are saying [ng-gapi](https://www.npmjs.com/package/ng-gapi) is working pretty nicely within Cordova? It's a bit frustrating to not find any valuable information about that topic. We want to have different users accessing different data on google sheets. But without any specific user interaction in the frontend of the app. So, what are you suggesting to me? =) 

Cheers,

Simon

**Comment by xinfengmich** [comment] 2019-04-15 20:28
ng-gapi works well within our ionic app.   My new testing result, gapi.client loads successfully with V2.4.1 , but still failed on V4.0.1 .

**Comment by jcesarmobile** [comment] 2019-04-22 14:37
Can you provide a sample app?

**Comment by jcesarmobile** [comment] 2019-06-10 12:26
Closing as the requested sample app was not provided and I need more information and a sample project if possible to reproduce.
Feel free to reopen if you can provide it.

**Closed by jcesarmobile** 2019-06-10 12:26 UTC
Labels: needs answer

**Comment by xinfengmich** [comment] 2020-04-17 14:20
[myApp.zip](https://github.com/ionic-team/cordova-plugin-ionic-webview/files/4493393/myApp.zip)
I uploaded a sample app here.  With 'ng serve', gapi.client loads fine, but still is NOT loaded with the latest cordova-plugin-ionic-webview V4.2.0 on iOS platform.  If downgrade to V2.4.1,  gapi.client is loaded then. 
This issue is blocking us to upgrade cordova-plugin-ionic-webview plugin while we try to fix "ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020." .   
Would you please reopen this issue? 
Really appreciate your help.  Thanks.
